import { board, w, p, f } from '../dsl.mjs';

export const boards = [
  board('play', 'Toys & Play', '🧸', 'noun', 8, 5, [
    f('Toys', '🧸', 'play_toys'),
    f('Outside', '🌳', 'play_outside'),
    f('Screens', '📺', 'play_screens'),
    f('Art', '🎨', 'play_art'),
    f('Music', '🎵', 'play_music'),
    f('Games', '🎲', 'play_games'),
    f('Pretend', '🦸', 'play_pretend'),
    f('Books', '📚', 'play_books'),

    w('play', '🧸', { color: 'verb', pos: 'verb', past: 'played', ing: 'playing' }),
    w('build', '🧱', { color: 'verb', pos: 'verb', past: 'built', ing: 'building' }),
    w('throw', '🤾', { color: 'verb', pos: 'verb', past: 'threw', ing: 'throwing' }),
    w('catch', '🙌', { color: 'verb', pos: 'verb', past: 'caught', ing: 'catching' }),
    w('hide', '🙈', { color: 'verb', pos: 'verb', past: 'hid', ing: 'hiding' }),
    w('run', '🏃', { color: 'verb', pos: 'verb', past: 'ran', ing: 'running' }),
    w('jump', '🤸', { color: 'verb', pos: 'verb', past: 'jumped', ing: 'jumping' }),
    w('swing', '🛝', { color: 'verb', pos: 'verb', past: 'swung', ing: 'swinging' }),

    p('my turn', '🙋', 'it is my turn', { color: 'social' }),
    p('your turn', '👉', 'it is your turn', { color: 'social' }),
    p('play with me', '🤝', 'will you play with me', { color: 'social' }),
    p('I want that one', '👆', 'I want that one', { color: 'social' }),
    p('not that one', '🙅', 'not that one', { color: 'negation' }),
    p('this is fun', '🎉', 'this is fun', { color: 'social' }),
    p("I'm bored", '😐', 'I am bored', { color: 'describe' }),
    p('play again', '🔁', 'I want to play again', { color: 'social' }),

    w('fun', '🎉', { color: 'describe' }),
    w('fast', '💨', { color: 'describe' }),
    w('slow', '🐌', { color: 'describe' }),
    w('high', '⬆️', { color: 'describe' }),
    w('again', '🔁', { color: 'describe' }),
    w('mine', '🙋', { color: 'people' }),
    w('yours', '👉', { color: 'people' }),
    w('together', '🤝', { color: 'describe' }),

    p('help me build', '🧱', 'help me build it', { color: 'social' }),
    p('it broke', '💔', 'it broke', { color: 'social' }),
    p('fix it please', '🔧', 'can you fix it please', { color: 'social' }),
    p('put it away', '📦', 'time to put it away', { color: 'verb' }),
    p('one more time', '☝️', 'one more time please', { color: 'social' }),
    p('I did it', '🏆', 'I did it', { color: 'social' }),
    p('watch me', '👀', 'watch me', { color: 'social' }),
    p('all done playing', '✅', 'I am all done playing', { color: 'social' }),
  ]),

  board('play_toys', 'Toys', '🧸', 'noun', 8, 3, [
    w('teddy bear', '🧸', { plural: 'teddy bears' }), w('doll', '🪆', { plural: 'dolls' }),
    w('blocks', '🧱'), w('lego', '🧱'), w('ball', '⚽', { plural: 'balls' }),
    w('car', '🚗', { plural: 'cars' }), w('train', '🚂', { plural: 'trains' }), w('puzzle', '🧩', { plural: 'puzzles' }),
    w('bubbles', '🫧'), w('slime', '🟢'), w('play dough', '🎨'), w('kite', '🪁', { plural: 'kites' }),
    w('robot', '🤖', { plural: 'robots' }), w('dinosaur', '🦕', { plural: 'dinosaurs' }),
    w('action figure', '🦸', { plural: 'action figures' }), w('stuffed animal', '🧸', { plural: 'stuffed animals' }),
    w('blanket', '🛏️', { plural: 'blankets' }), w('balloon', '🎈', { plural: 'balloons' }),
    w('marble', '🔮', { plural: 'marbles' }), w('yo-yo', '🪀'),
    w('fidget toy', '🌀', { plural: 'fidget toys' }), w('sensory toy', '🌀'),
    w('doll house', '🏠'), w('toy box', '📦'),
  ]),

  board('play_outside', 'Outside', '🌳', 'noun', 8, 3, [
    w('park', '🏞️'), w('playground', '🛝'), w('swing', '🛝', { plural: 'swings' }),
    w('slide', '🛝', { plural: 'slides' }), w('sandbox', '🏖️'), w('bike', '🚲', { plural: 'bikes' }),
    w('scooter', '🛴'), w('swimming', '🏊'), w('pool', '🏊'), w('beach', '🏖️'),
    w('grass', '🌱'), w('tree', '🌳', { plural: 'trees' }), w('flower', '🌸', { plural: 'flowers' }),
    w('rock', '🪨', { plural: 'rocks' }), w('stick', '🪵', { plural: 'sticks' }), w('puddle', '💧', { plural: 'puddles' }),
    w('rain', '🌧️'), w('snow', '❄️'), w('sun', '☀️'), w('wind', '🌬️'),
    p('go outside', '🚪', 'I want to go outside', { color: 'social' }),
    p('go home now', '🏠', 'I want to go home now', { color: 'social' }),
    p('too hot outside', '🥵', 'it is too hot outside', { color: 'describe' }),
    p('I need my shoes', '👟', 'I need my shoes', { color: 'social' }),
  ]),

  board('play_screens', 'Screens', '📺', 'noun', 8, 2, [
    w('tablet', '📱'), w('TV', '📺'), w('phone', '📱'), w('computer', '💻'),
    w('video', '🎬', { plural: 'videos' }), w('movie', '🎥', { plural: 'movies' }),
    w('show', '📺', { plural: 'shows' }), w('game', '🎮', { plural: 'games' }),
    w('headphones', '🎧'), w('volume up', '🔊'), w('volume down', '🔉'), w('pause', '⏸️'),
    p('my show please', '📺', 'can I watch my show please', { color: 'social' }),
    p('turn it on', '🔛', 'turn it on please', { color: 'verb' }),
    p('turn it off', '🔴', 'turn it off please', { color: 'verb' }),
    p('too loud', '📢', 'it is too loud', { color: 'urgent' }),
  ]),

  board('play_art', 'Art & Craft', '🎨', 'noun', 8, 2, [
    w('draw', '✏️', { color: 'verb', past: 'drew', ing: 'drawing' }),
    w('color', '🖍️', { color: 'verb', past: 'colored', ing: 'coloring' }),
    w('paint', '🎨', { color: 'verb', past: 'painted', ing: 'painting' }),
    w('cut', '✂️', { color: 'verb', past: 'cut', ing: 'cutting' }),
    w('glue', '🩹', { color: 'verb', past: 'glued', ing: 'gluing' }), w('sticker', '⭐', { plural: 'stickers' }),
    w('crayon', '🖍️', { plural: 'crayons' }), w('marker', '🖊️', { plural: 'markers' }),
    w('paper', '📄'), w('scissors', '✂️'), w('paint brush', '🖌️'), w('play dough', '🟡'),
    p('I made this', '🖼️', 'I made this', { color: 'social' }),
    p('look at my picture', '🖼️', 'look at my picture', { color: 'social' }),
    p('I need more paper', '📄', 'I need more paper', { color: 'social' }),
    p('messy hands', '🖐️', 'my hands are messy', { color: 'social' }),
  ]),

  board('play_music', 'Music', '🎵', 'noun', 8, 2, [
    w('music', '🎵'), w('song', '🎶', { plural: 'songs' }), w('sing', '🎤', { color: 'verb', past: 'sang', ing: 'singing' }),
    w('dance', '💃', { color: 'verb', past: 'danced', ing: 'dancing' }),
    w('drum', '🥁', { plural: 'drums' }), w('piano', '🎹'), w('guitar', '🎸'), w('shaker', '🪇'),
    w('loud', '📢', { color: 'describe' }), w('quiet', '🤫', { color: 'describe' }),
    w('louder', '🔊', { color: 'describe' }), w('softer', '🔉', { color: 'describe' }),
    p('play my song', '🎵', 'play my song please', { color: 'social' }),
    p('dance with me', '💃', 'dance with me', { color: 'social' }),
    p('music off please', '🔇', 'turn the music off please', { color: 'social' }),
    p('I like this song', '❤️', 'I like this song', { color: 'social' }),
  ]),

  board('play_games', 'Games', '🎲', 'noun', 8, 2, [
    w('hide and seek', '🙈'), w('tag', '🏃'), w('chase', '🏃'), w('peekaboo', '🫣'),
    w('board game', '🎲', { plural: 'board games' }), w('cards', '🃏'), w('puzzle', '🧩'), w('race', '🏁'),
    w('win', '🏆', { color: 'verb', past: 'won' }), w('lose', '😢', { color: 'verb', past: 'lost' }),
    w('turn', '🔄', { plural: 'turns' }), w('rules', '📋'),
    p('I want to win', '🏆', 'I want to win', { color: 'social' }),
    p("that's not fair", '⚖️', 'that is not fair', { color: 'social' }),
    p('play with me', '🤝', 'will you play with me', { color: 'social' }),
    p('I want to stop', '🛑', 'I want to stop playing', { color: 'social' }),
  ]),

  board('play_pretend', 'Pretend', '🦸', 'noun', 8, 2, [
    w('pretend', '🎭', { color: 'verb', past: 'pretended', ing: 'pretending' }), w('superhero', '🦸'), w('princess', '👸'), w('pirate', '🏴‍☠️'),
    w('doctor', '🩺'), w('teacher', '🧑‍🏫'), w('chef', '👨‍🍳'), w('astronaut', '👨‍🚀'),
    w('dragon', '🐉'), w('monster', '👹'), w('fairy', '🧚'), w('animal', '🐾'),
    w('castle', '🏰'), w('rocket', '🚀'), w('magic', '✨'), w('costume', '🎭'),
  ]),

  board('play_books', 'Books & Stories', '📚', 'noun', 8, 2, [
    w('book', '📖', { plural: 'books' }), w('story', '📚', { plural: 'stories' }),
    w('read', '📖', { color: 'verb', past: 'read', ing: 'reading' }),
    w('picture', '🖼️', { plural: 'pictures' }),
    w('page', '📄', { plural: 'pages' }), w('turn the page', '👉'), w('again', '🔁'), w('the end', '🔚'),
    p('read to me', '📖', 'will you read to me', { color: 'social' }),
    p('I want this book', '📕', 'I want this book', { color: 'social' }),
    p('read it again', '🔁', 'read it again please', { color: 'social' }),
    p('my favorite', '⭐', 'this is my favorite', { color: 'social' }),
    p('turn the page', '👉', 'turn the page please', { color: 'social' }),
    p("what's that?", '❓', 'what is that', { color: 'question' }),
    p('I like this part', '❤️', 'I like this part', { color: 'social' }),
    p('all done reading', '✅', 'I am all done reading', { color: 'social' }),
  ]),
];
