import { board, w, p, f } from '../dsl.mjs';

export const boards = [
  board('household', 'Things Around Me', '🛋️', 'noun', 8, 4, [
    f('Kitchen', '🍳', 'household_kitchen'),
    f('Bedroom', '🛏️', 'household_bedroom'),
    f('Bathroom', '🛁', 'household_bathroom'),
    f('Living room', '🛋️', 'household_living'),
    f('Outside', '🌳', 'play_outside'),
    f('Car', '🚗', 'household_car'),
    f('Clothes', '👕', 'clothes'),
    f('School', '✏️', 'school'),

    w('light', '💡', { plural: 'lights' }), w('door', '🚪', { plural: 'doors' }),
    w('window', '🪟', { plural: 'windows' }), w('chair', '🪑', { plural: 'chairs' }),
    w('table', '🪑', { plural: 'tables' }), w('bed', '🛏️', { plural: 'beds' }),
    w('phone', '📱', { plural: 'phones' }), w('key', '🔑', { plural: 'keys' }),
    w('bag', '🎒', { plural: 'bags' }), w('box', '📦', { plural: 'boxes' }),
    w('trash', '🗑️'), w('clock', '⏰', { plural: 'clocks' }),
    w('money', '💵'), w('battery', '🔋', { plural: 'batteries' }),
    w('charger', '🔌', { plural: 'chargers' }), w('remote', '📱', { plural: 'remotes' }),

    p('turn the light on', '💡', 'turn the light on please', { color: 'verb' }),
    p('turn the light off', '🌑', 'turn the light off please', { color: 'verb' }),
    p('open the door', '🚪', 'open the door please', { color: 'verb' }),
    p('I need my bag', '🎒', 'I need my bag', { color: 'social' }),
    p('where is my stuff?', '❓', 'where is my stuff', { color: 'question' }),
    p("it's not working", '⚠️', 'it is not working', { color: 'social' }),
    p('I need help with this', '🆘', 'I need help with this', { color: 'urgent' }),
    p('put it here', '📍', 'put it here please', { color: 'verb' }),
  ]),

  board('household_kitchen', 'Kitchen', '🍳', 'noun', 8, 2, [
    w('fridge', '🧊'), w('oven', '🔥'), w('microwave', '📻'), w('sink', '🚰'),
    w('cup', '🥛', { plural: 'cups' }), w('plate', '🍽️', { plural: 'plates' }),
    w('bowl', '🥣', { plural: 'bowls' }), w('spoon', '🥄', { plural: 'spoons' }),
    w('fork', '🍴', { plural: 'forks' }), w('pot', '🍲', { plural: 'pots' }),
    w('lunch box', '🧰'), w('snack', '🍿', { plural: 'snacks' }),
    w('water', '💧'), w('ice', '🧊'), w('towel', '🧻'), w('trash', '🗑️'),
  ]),

  board('household_bedroom', 'Bedroom', '🛏️', 'noun', 8, 2, [
    w('bed', '🛏️'), w('pillow', '🛌', { plural: 'pillows' }), w('blanket', '🧶', { plural: 'blankets' }),
    w('lamp', '💡', { plural: 'lamps' }), w('closet', '🚪'), w('drawer', '🗄️', { plural: 'drawers' }),
    w('pajamas', '🩱'), w('night light', '🌙'),
    w('stuffed animal', '🧸'), w('book', '📖', { plural: 'books' }), w('toy box', '📦'), w('rug', '🟫'),
    p('I want to go to bed', '🛏️', 'I want to go to bed', { color: 'social' }),
    p("I can't sleep", '😣', 'I cannot sleep', { color: 'social' }),
    p('leave the light on', '💡', 'leave the light on please', { color: 'social' }),
    p('I had a bad dream', '😰', 'I had a bad dream', { color: 'urgent' }),
  ]),

  board('household_bathroom', 'Bathroom', '🛁', 'noun', 8, 2, [
    w('toilet', '🚽'), w('sink', '🚰'), w('bath', '🛁'), w('shower', '🚿'),
    w('soap', '🧼'), w('towel', '🧻'), w('toilet paper', '🧻'), w('toothbrush', '🪥'),
    w('mirror', '🪞'), w('potty', '🚽'), w('wipes', '🧻'), w('tissue', '🤧'),
    p('I need the bathroom', '🚽', 'I need to go to the bathroom', { color: 'urgent' }),
    p("I'm done", '✅', 'I am done', { color: 'social' }),
    p('I need help wiping', '🧻', 'I need help wiping', { color: 'urgent' }),
    p('the water is too hot', '🥵', 'the water is too hot', { color: 'urgent' }),
  ]),

  board('household_living', 'Living Room', '🛋️', 'noun', 8, 2, [
    w('couch', '🛋️'), w('TV', '📺'), w('remote', '📱'), w('lamp', '💡'),
    w('rug', '🟫'), w('pillow', '🛌'), w('blanket', '🧶'), w('window', '🪟'),
    w('tablet', '📱'), w('game', '🎮'), w('book', '📖'), w('music', '🎵'),
    p('I want to watch TV', '📺', 'I want to watch TV', { color: 'social' }),
    p('sit with me', '🛋️', 'come sit with me', { color: 'social' }),
    p('I want a blanket', '🧶', 'I want a blanket', { color: 'social' }),
    p('too loud in here', '📢', 'it is too loud in here', { color: 'urgent' }),
  ]),

  board('household_car', 'In the Car', '🚗', 'noun', 8, 2, [
    w('car', '🚗'), w('seat belt', '💺'), w('car seat', '💺'), w('window', '🪟'),
    w('radio', '📻'), w('door', '🚪'), w('bus', '🚌'), w('walk', '🚶'),
    p('are we there yet?', '❓', 'are we there yet', { color: 'question' }),
    p('where are we going?', '📍', 'where are we going', { color: 'question' }),
    p('I feel sick in the car', '🤢', 'I feel sick in the car', { color: 'urgent' }),
    p('music please', '🎵', 'can we have music please', { color: 'social' }),
    p('too hot in here', '🥵', 'it is too hot in here', { color: 'urgent' }),
    p('I want my window open', '🪟', 'I want my window open', { color: 'social' }),
    p('I dropped something', '⬇️', 'I dropped something', { color: 'social' }),
    p('I want to get out', '🚪', 'I want to get out', { color: 'urgent' }),
  ]),

  board('clothes', 'Clothes', '👕', 'noun', 8, 3, [
    w('shirt', '👕', { plural: 'shirts' }), w('pants', '👖'), w('dress', '👗', { plural: 'dresses' }),
    w('skirt', '👗', { plural: 'skirts' }), w('shorts', '🩳'), w('socks', '🧦'),
    w('shoes', '👟'), w('boots', '👢'),
    w('coat', '🧥', { plural: 'coats' }), w('hat', '🧢', { plural: 'hats' }),
    w('gloves', '🧤'), w('scarf', '🧣'), w('pajamas', '🩱'), w('underwear', '🩲'),
    w('swimsuit', '🩱'), w('sweater', '🧥', { plural: 'sweaters' }),
    p('I want to get dressed', '👕', 'I want to get dressed', { color: 'social' }),
    p('help me put it on', '🤝', 'help me put it on', { color: 'social' }),
    p('it feels scratchy', '😣', 'it feels scratchy on my skin', { color: 'urgent' }),
    p('too tight', '😖', 'it is too tight', { color: 'urgent' }),
    p("I don't want to wear that", '🙅', 'I do not want to wear that', { color: 'negation' }),
    p('I want my soft clothes', '☁️', 'I want my soft clothes', { color: 'social' }),
    p('my shoes are off', '👟', 'my shoes are off', { color: 'social' }),
    p("I'm cold", '🥶', 'I am cold', { color: 'social' }),
  ]),

  board('animals', 'Animals & Nature', '🐶', 'noun', 8, 4, [
    w('dog', '🐶', { plural: 'dogs' }), w('cat', '🐱', { plural: 'cats' }),
    w('bird', '🐦', { plural: 'birds' }), w('fish', '🐟'),
    w('horse', '🐴', { plural: 'horses' }), w('cow', '🐮', { plural: 'cows' }),
    w('pig', '🐷', { plural: 'pigs' }), w('sheep', '🐑'),
    w('rabbit', '🐰', { plural: 'rabbits' }), w('mouse', '🐭', { plural: 'mice' }),
    w('bear', '🐻', { plural: 'bears' }), w('lion', '🦁', { plural: 'lions' }),
    w('elephant', '🐘', { plural: 'elephants' }), w('monkey', '🐵', { plural: 'monkeys' }),
    w('giraffe', '🦒', { plural: 'giraffes' }), w('penguin', '🐧', { plural: 'penguins' }),
    w('butterfly', '🦋', { plural: 'butterflies' }), w('bee', '🐝', { plural: 'bees' }),
    w('spider', '🕷️', { plural: 'spiders' }), w('duck', '🦆', { plural: 'ducks' }),
    w('frog', '🐸', { plural: 'frogs' }), w('turtle', '🐢', { plural: 'turtles' }),
    w('dinosaur', '🦕', { plural: 'dinosaurs' }), w('unicorn', '🦄', { plural: 'unicorns' }),
    w('tree', '🌳', { plural: 'trees' }), w('flower', '🌸', { plural: 'flowers' }),
    w('bug', '🐛', { plural: 'bugs' }), w('water', '💧'),
    p('I want to pet it', '🤚', 'can I pet it', { color: 'question' }),
    p("it's too big", '🐘', 'it is too big', { color: 'social' }),
    p("I'm scared of it", '😨', 'I am scared of it', { color: 'urgent' }),
    p('look at the animal', '👀', 'look at the animal', { color: 'social' }),
  ]),

  board('school', 'School', '✏️', 'noun', 8, 5, [
    w('teacher', '🧑‍🏫', { color: 'people' }), w('friend', '🧒', { color: 'people', plural: 'friends' }),
    w('class', '🏫'), w('desk', '🪑'), w('chair', '🪑'), w('backpack', '🎒'),
    w('pencil', '✏️', { plural: 'pencils' }), w('paper', '📄'),
    w('book', '📖', { plural: 'books' }), w('crayon', '🖍️', { plural: 'crayons' }),
    w('scissors', '✂️'), w('glue', '🩹'), w('computer', '💻'), w('whiteboard', '📋'),
    w('lunch', '🍱'), w('recess', '🛝'),
    w('circle time', '⭕'), w('story time', '📚'), w('music class', '🎵'), w('gym', '🤸'),
    w('bus', '🚌'), w('line', '🚶'), w('quiet time', '🤫'), w('homework', '📝'),
    p('I need help with my work', '🆘', 'I need help with my work', { color: 'urgent' }),
    p("I'm finished", '✅', 'I am finished', { color: 'social' }),
    p("I don't understand", '😕', 'I do not understand', { color: 'social' }),
    p('can I have a break?', '⏸️', 'can I have a break please', { color: 'urgent' }),
    p('I need the bathroom', '🚽', 'I need to go to the bathroom', { color: 'urgent' }),
    p('what do I do?', '❓', 'what do I do now', { color: 'question' }),
    p('I want to work alone', '🚶', 'I want to work alone', { color: 'social' }),
    p('this is too hard', '😤', 'this is too hard for me', { color: 'urgent' }),

    // Learning hub. She is reading, spelling and learning her flags, so the
    // things she is being taught get their own way in.
    f('Letters', '🔤', 'keyboard', { color: 'social' }),
    f('Numbers', '🔢', 'numbers', { color: 'describe' }),
    f('Flags', '🌍', 'world'),
    f('Building words', '🧩', 'build', { color: 'social' }),
    f('Colors', '🌈', 'describe_colors', { color: 'describe' }),
    f('Shapes', '🔷', 'describe_shapes', { color: 'describe' }),
    f('Opposites', '↔️', 'describe_opposites', { color: 'describe' }),
    f('Time', '⏰', 'time', { color: 'describe' }),
  ]),

  board('numbers', 'Numbers & Counting', '🔢', 'describe', 8, 3, [
    w('one', '1️⃣'), w('two', '2️⃣'), w('three', '3️⃣'), w('four', '4️⃣'),
    w('five', '5️⃣'), w('six', '6️⃣'), w('seven', '7️⃣'), w('eight', '8️⃣'),
    w('nine', '9️⃣'), w('ten', '🔟'), w('zero', '0️⃣'), w('more', '➕'),
    w('less', '➖'), w('all', '💯'), w('none', '🚫', { color: 'negation' }), w('half', '➗'),
    w('first', '🥇'), w('second', '🥈'), w('last', '🏁'), w('how many', '❓', { color: 'question' }),
    w('a lot', '💯'), w('a little', '🤏'), w('enough', '✋'), w('too many', '🙌'),
  ]),

  board('time', 'Time', '⏰', 'describe', 8, 3, [
    w('now', '⏱️'), w('later', '⏳'), w('soon', '⏰'), w('wait', '✋'),
    w('today', '📅'), w('tomorrow', '➡️'), w('yesterday', '⬅️'), w('again', '🔁'),
    w('morning', '🌅'), w('afternoon', '☀️'), w('night', '🌙'), w('bedtime', '🛏️'),
    w('first', '1️⃣'), w('then', '2️⃣'), w('last', '🏁'), w('all done', '✅'),
    w('before', '⬅️'), w('after', '➡️'), w('fast', '💨'), w('slow', '🐌'),
    p('how long?', '❓', 'how long until then', { color: 'question' }),
    p('I want it now', '⏱️', 'I want it now', { color: 'social' }),
    p("what's next?", '➡️', 'what is next', { color: 'question' }),
    p('five more minutes', '5️⃣', 'five more minutes please', { color: 'social' }),
  ]),
];
