import { board, w, p, f } from '../dsl.mjs';

export const boards = [
  // Family buttons are deliberately generic. A parent swaps in real names and
  // photos from Edit mode; the ids stay stable so the layout never shifts.
  board('people', 'People', '👨‍👩‍👧', 'people', 8, 4, [
    w('Mom', '👩'), w('Dad', '👨'), w('Grandma', '👵'), w('Grandpa', '👴'),
    w('sister', '👧', { plural: 'sisters' }), w('brother', '👦', { plural: 'brothers' }),
    w('baby', '👶', { plural: 'babies' }), w('family', '👨‍👩‍👧'),
    w('friend', '🧒', { plural: 'friends' }), w('teacher', '🧑‍🏫', { plural: 'teachers' }),
    w('doctor', '🩺'), w('nurse', '🧑‍⚕️'), w('helper', '🤝'), w('bus driver', '🚌'),
    w('neighbor', '🏘️'), w('everybody', '👥'),
    w('I', '🙋', { pos: 'pronoun' }), w('me', '👇', { pos: 'pronoun' }), w('my', '🤲', { pos: 'pronoun' }),
    w('you', '👉', { pos: 'pronoun' }), w('your', '🫵', { pos: 'pronoun' }),
    w('we', '👥', { pos: 'pronoun' }), w('they', '👬', { pos: 'pronoun' }),
    w('he', '👦', { pos: 'pronoun' }),
    w('she', '👧', { pos: 'pronoun' }), w('it', '📦', { pos: 'pronoun' }),
    w('them', '👫', { pos: 'pronoun' }), w('us', '🫂', { pos: 'pronoun' }),
    p("what's your name?", '❓', 'what is your name', { color: 'question' }),
    p('come here please', '👋', 'come here please', { color: 'social' }),
    p('I want Mom', '👩', 'I want Mom', { color: 'social' }),
    p('I miss you', '🥺', 'I miss you', { color: 'social' }),
  ]),

  board('places', 'Places & Going', '🏫', 'noun', 8, 5, [
    w('home', '🏠'), w('school', '🏫'), w('store', '🏪'), w('park', '🏞️'),
    w('car', '🚗'), w('outside', '🌳'), w('inside', '🚪'), w("Grandma's house", '🏡'),
    w('restaurant', '🍽️'), w('doctor', '🏥'), w('library', '📚'), w('pool', '🏊'),
    w('playground', '🛝'), w('bus', '🚌'), w('church', '⛪'), w('beach', '🏖️'),
    w('go', '➡️', { color: 'verb', past: 'went', ing: 'going' }),
    w('come', '⬅️', { color: 'verb', past: 'came', ing: 'coming' }),
    w('stay', '🛑', { color: 'verb', past: 'stayed', ing: 'staying' }),
    w('leave', '🚪', { color: 'verb', past: 'left', ing: 'leaving' }),
    w('in', '📥', { color: 'describe' }), w('out', '📤', { color: 'describe' }),
    w('up', '⬆️', { color: 'describe' }), w('down', '⬇️', { color: 'describe' }),
    w('here', '📍', { color: 'describe' }), w('there', '👉', { color: 'describe' }),
    w('under', '⬇️', { color: 'describe' }), w('on top', '⬆️', { color: 'describe' }),
    w('behind', '🔙', { color: 'describe' }), w('next to', '↔️', { color: 'describe' }),
    w('far', '🔭', { color: 'describe' }), w('close', '🤏', { color: 'describe' }),
    p('I want to go home', '🏠', 'I want to go home', { color: 'social' }),
    p('are we there yet?', '❓', 'are we there yet', { color: 'question' }),
    p('where are we going?', '❓', 'where are we going', { color: 'question' }),
    p("I don't want to go", '🙅', 'I do not want to go', { color: 'negation' }),
  ]),

  board('actions', 'Doing Words', '🏃', 'verb', 8, 5, [
    w('go', '➡️', { past: 'went', ing: 'going' }), w('stop', '🛑', { past: 'stopped', ing: 'stopping' }),
    w('get', '🫴', { past: 'got', ing: 'getting' }), w('give', '🎁', { past: 'gave', ing: 'giving' }),
    w('put', '📥', { past: 'put', ing: 'putting' }), w('take', '🤲', { past: 'took', ing: 'taking' }),
    w('make', '🔨', { past: 'made', ing: 'making' }), w('do', '✅', { past: 'did', ing: 'doing' }),
    w('play', '🧸', { past: 'played', ing: 'playing' }), w('eat', '😋', { past: 'ate', ing: 'eating' }),
    w('drink', '🥛', { past: 'drank', ing: 'drinking' }), w('sleep', '😴', { past: 'slept', ing: 'sleeping' }),
    w('look', '👀', { past: 'looked', ing: 'looking' }), w('see', '👁️', { past: 'saw', ing: 'seeing' }),
    w('hear', '👂', { past: 'heard', ing: 'hearing' }), w('say', '🗣️', { past: 'said', ing: 'saying' }),
    w('open', '🔓', { past: 'opened', ing: 'opening' }), w('close', '🔒', { past: 'closed', ing: 'closing' }),
    w('turn on', '🔛', { past: 'turned on', ing: 'turning on' }), w('turn off', '🔴', { past: 'turned off', ing: 'turning off' }),
    w('wash', '🧼', { past: 'washed', ing: 'washing' }), w('read', '📖', { past: 'read', ing: 'reading' }),
    w('watch', '📺', { past: 'watched', ing: 'watching' }), w('wait', '✋', { past: 'waited', ing: 'waiting' }),
    w('sit', '🪑', { past: 'sat', ing: 'sitting' }), w('stand', '🧍', { past: 'stood', ing: 'standing' }),
    w('walk', '🚶', { past: 'walked', ing: 'walking' }), w('run', '🏃', { past: 'ran', ing: 'running' }),
    w('jump', '🤸', { past: 'jumped', ing: 'jumping' }), w('hug', '🤗', { past: 'hugged', ing: 'hugging' }),
    w('hold', '🤝', { past: 'held', ing: 'holding' }), w('help', '🆘', { past: 'helped', ing: 'helping' }),
    w('find', '🔍', { past: 'found', ing: 'finding' }), w('fix', '🔧', { past: 'fixed', ing: 'fixing' }),
    w('push', '👐', { past: 'pushed', ing: 'pushing' }), w('pull', '🪢', { past: 'pulled', ing: 'pulling' }),
    w('share', '🤝', { past: 'shared', ing: 'sharing' }), w('try', '💪', { past: 'tried', ing: 'trying' }),
    w('think', '🤔', { past: 'thought', ing: 'thinking' }), w('feel', '💗', { past: 'felt', ing: 'feeling' }),
  ]),

  board('describe', 'Describing Words', '🌈', 'describe', 8, 5, [
    f('Colors', '🌈', 'describe_colors'),
    f('Opposites', '↔️', 'describe_opposites'),
    f('Shapes', '🔷', 'describe_shapes'),
    f('Weather', '🌤️', 'describe_weather'),
    w('big', '🐘'), w('little', '🐜'), w('more', '➕'), w('all gone', '🫗'),
    w('hot', '🔥'), w('cold', '🧊'), w('wet', '💧'), w('dry', '🏜️'),
    w('loud', '📢'), w('quiet', '🤫'), w('fast', '💨'), w('slow', '🐌'),
    w('good', '👍'), w('bad', '👎'), w('funny', '😂'), w('scary', '😱'),
    w('pretty', '🌸'), w('soft', '☁️'), w('hard', '🪨'), w('sticky', '🍯'),
    w('dirty', '🧺'), w('clean', '✨'), w('broken', '💔'), w('new', '✨'),
    w('same', '🟰'), w('different', '🔀'), w('all', '💯'), w('some', '🤏'),
    w('none', '🚫', { color: 'negation' }), w('too much', '🙌'), w('enough', '✋'), w('favorite', '⭐'),
    p("that's silly", '🤪', 'that is silly', { color: 'social' }),
    p('I like that', '👍', 'I like that', { color: 'social' }),
    p("it's too big", '🐘', 'it is too big', { color: 'social' }),
    p("it's broken", '💔', 'it is broken', { color: 'social' }),
  ]),

  board('describe_colors', 'Colors', '🌈', 'describe', 8, 2, [
    w('red', '🟥'), w('orange', '🟧'), w('yellow', '🟨'), w('green', '🟩'),
    w('blue', '🟦'), w('purple', '🟪'), w('pink', '💗'), w('brown', '🟫'),
    w('black', '⬛'), w('white', '⬜'), w('gray', '🩶'), w('rainbow', '🌈'),
    w('gold', '🟡'), w('silver', '⚪'), w('light', '💡'), w('dark', '🌑'),
  ]),

  board('describe_opposites', 'Opposites', '↔️', 'describe', 8, 3, [
    w('big', '🐘'), w('little', '🐜'), w('hot', '🔥'), w('cold', '🧊'),
    w('fast', '💨'), w('slow', '🐌'), w('loud', '📢'), w('quiet', '🤫'),
    w('happy', '😀'), w('sad', '😢'), w('up', '⬆️'), w('down', '⬇️'),
    w('in', '📥'), w('out', '📤'), w('open', '🔓'), w('closed', '🔒'),
    w('dirty', '🧺'), w('clean', '✨'), w('wet', '💧'), w('dry', '🏜️'),
    w('full', '🥛'), w('empty', '🫗'), w('on', '🔛'), w('off', '🔴'),
  ]),

  board('describe_shapes', 'Shapes & Sizes', '🔷', 'describe', 8, 2, [
    w('circle', '⭕'), w('square', '⬜'), w('triangle', '🔺'), w('star', '⭐'),
    w('heart', '❤️'), w('diamond', '💎'), w('rectangle', '▭'), w('oval', '🥚'),
    w('big', '🐘'), w('small', '🐜'), w('long', '📏'), w('short', '📐'),
    w('tall', '🦒'), w('round', '⭕'), w('flat', '🟫'), w('pointy', '📌'),
  ]),

  board('describe_weather', 'Weather & Outside', '🌤️', 'describe', 8, 2, [
    w('sunny', '☀️'), w('rainy', '🌧️'), w('cloudy', '☁️'), w('snowy', '❄️'),
    w('windy', '🌬️'), w('stormy', '⛈️'), w('hot', '🥵'), w('cold', '🥶'),
    w('rainbow', '🌈'), w('moon', '🌙'), w('stars', '⭐'), w('sky', '🌤️'),
    p("it's raining", '🌧️', 'it is raining', { color: 'social' }),
    p('I need a coat', '🧥', 'I need my coat', { color: 'social' }),
    p('too hot for me', '🥵', 'it is too hot for me', { color: 'urgent' }),
    p('I want to go outside', '🌳', 'I want to go outside', { color: 'social' }),
  ]),

  board('social', 'Words & Questions', '💬', 'social', 8, 5, [
    w('who', '❓', { color: 'question' }), w('what', '❓', { color: 'question' }),
    w('where', '📍', { color: 'question' }), w('when', '⏰', { color: 'question' }),
    w('why', '❓', { color: 'question' }), w('how', '❓', { color: 'question' }),
    w('which', '🤔', { color: 'question' }), w('how many', '🔢', { color: 'question' }),
    w('yes', '✅'), w('no', '❌', { color: 'negation' }), w('maybe', '🤷'), w('okay', '👌'),
    w('please', '🙏'), w('thank you', '🙇'), w('sorry', '😔'), w('excuse me', '🙋'),
    w('hi', '👋'), w('bye', '👋'), w('good morning', '🌅'), w('good night', '🌙'),
    p("what's that?", '❓', 'what is that', { color: 'question' }),
    p('where is it?', '📍', 'where is it', { color: 'question' }),
    p('who is that?', '❓', 'who is that', { color: 'question' }),
    p('can I have it?', '🤲', 'can I have it please', { color: 'question' }),
    p('can you help me?', '🆘', 'can you help me please', { color: 'question' }),
    p('is it my turn?', '🙋', 'is it my turn', { color: 'question' }),
    p('what happens next?', '➡️', 'what happens next', { color: 'question' }),
    p('can we go?', '🚪', 'can we go now', { color: 'question' }),
    p("I don't know", '🤷', 'I do not know'),
    p("I don't understand", '😕', 'I do not understand'),
    p('say it again', '🔁', 'can you say it again'),
    p('I have something to say', '🗣️', 'I have something to say'),
    p('listen to me', '👂', 'please listen to me'),
    p('my name is', '🏷️', 'my name is'),
    p('nice to meet you', '🤝', 'nice to meet you'),
    p('see you later', '👋', 'see you later'),
  ]),
];
